Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -5,8 +5,6 @@ on:
     workflows:
       - 'CI'
     push:
-      tags:
-        - 'v[0-9.]+'
     types:
       - 'completed'
 
@@ -18,12 +16,13 @@ jobs:
 
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
 
-    steps:
-      - name: 'Detect & Set current tag'
-        run: |
-          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+    env:
+      LANG: 'C'
 
+    steps:
       - uses: 'actions/checkout@v2'
+        with:
+          fetch-depth: 0
 
       - name: 'Set up SSH key'
         env:
@@ -50,6 +49,26 @@ jobs:
       - name: 'Set up PHP version 8.0'
         run: |
           sudo update-alternatives --set php /usr/bin/php8.0
+
+      - name: 'Check version tag'
+        run: |
+          COMMIT_REVISION=$(git log -n 1 --pretty='format:%H')
+          echo "Current Revision: $COMMIT_REVISION"
+
+          if ! [[ $COMMIT_REVISION =~ ^[0-9a-f]+$ ]]; then
+            echo "Failed to get commit revision"
+            exit 1
+          fi
+
+          CURRENT_VERSION=$(git tag --points-at=$COMMIT_REVISION | grep '^v[0-9]' | sort -r --version-sort | head -n 1)
+          echo "Current Version: $CURRENT_VERSION"
+
+          if [ -z "$CURRENT_VERSION" ]; then
+            echo "This is not a release commit. exit."
+            exit 0
+          fi
+
+          echo "RELEASE_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
 
       - name: 'Deploy ${{ env.RELEASE_VERSION }}'
         run: |
